### ISSUE TITLE
example code: ERROR: MethodError: no method matching barthann(::Int64; dtype=Float32)

### ISSUE THREAD

**Issue by StefanPofahl** [sonosole/WindowFunctions.jl#2]
Hi,

please check your example code, the execution fails on my computer with the following error message.

Regards,

Stefan

```
ERROR: MethodError: no method matching barthann(::Int64; dtype=Float32)
Closest candidates are:
  barthann(::Int64) at /home/stefan/.julia/packages/WindowFunctions/fYhHv/src/1-unary.jl:12 got unsupported keyword argument "dtype"
Stacktrace:
 [1] top-level scope
   @ /media/stefan/DATA/data/julia/tmp/test_windowfunctions.jl:20
```

**Comment by sonosole** [comment]
Hi Stefan,

It has not been pushed to the official repo of Julia, so before this, use cmd
`pkg> add https://github.com/sonosole/WindowFunctions.jl.git#master`
to use this repo. I just tested the example in julia1.7.2, it worked good.

kind regards.

**Comment by StefanPofahl** [comment]
Under Linux I had the following error message:
```
(@v1.6) pkg> add https://github.com/sonosole/WindowFunctions.jl.git#master
     Cloning git-repo `https://github.com/sonosole/WindowFunctions.jl.git`
    Updating git-repo `https://github.com/sonosole/WindowFunctions.jl.git`
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
ERROR: expected package `VSCodeServer [9f5989ce]` to exist at path `/home/stefan/.vscode/extensions/julialang.language-julia-1.7.12/scripts/packages/VSCodeServer`
```
But this is probably a minor issue.

**Comment by StefanPofahl** [comment]
I have trouble to run your example code under linux:
```
ERROR: LoadError: MethodError: no method matching barthann(::Int64; dtype=Float32)
Closest candidates are:
  barthann(::Int64) at /home/stefan/.julia/packages/WindowFunctions/fYhHv/src/1-unary.jl:12 got unsupported keyword argument "dtype"
Stacktrace:
 [1] top-level scope
   @ /media/stefan/DATA/data/julia/tmp/test_windowfunctions.jl:25
 [2] include(fname::String)
   @ Base.MainInclude ./client.jl:444
 [3] top-level scope
   @ REPL[1]:1
in expression starting at /media/stefan/DATA/data/julia/tmp/test_windowfunctions.jl:24
```

**Comment by sonosole** [comment]
> I have trouble to run your example code under linux:
> ```
> ERROR: LoadError: MethodError: no method matching barthann(::Int64; dtype=Float32)
> Closest candidates are:
>   barthann(::Int64) at /home/stefan/.julia/packages/WindowFunctions/fYhHv/src/1-unary.jl:12 got unsupported keyword argument "dtype"
> Stacktrace:
>  [1] top-level scope
>    @ /media/stefan/DATA/data/julia/tmp/test_windowfunctions.jl:25
>  [2] include(fname::String)
>    @ Base.MainInclude ./client.jl:444
>  [3] top-level scope
>    @ REPL[1]:1
> in expression starting at /media/stefan/DATA/data/julia/tmp/test_windowfunctions.jl:24
> ```
barthann(::Int64) is the API from 0.1.0 , the keyword one is from 0.1.1, are you sure the 0.1.1 version has been added?  can i have a look at your pkg status?

**Comment by sonosole** [comment]
> Under Linux I had the following error message:
> 
> ```
> (@v1.6) pkg> add https://github.com/sonosole/WindowFunctions.jl.git#master
>      Cloning git-repo `https://github.com/sonosole/WindowFunctions.jl.git`
>     Updating git-repo `https://github.com/sonosole/WindowFunctions.jl.git`
>     Updating registry at `~/.julia/registries/General`
>    Resolving package versions...
> ERROR: expected package `VSCodeServer [9f5989ce]` to exist at path `/home/stefan/.vscode/extensions/julialang.language-julia-1.7.12/scripts/packages/VSCodeServer`
> ```
> 
> But this is probably a minor issue.

I tested this pkg under both Linux and win7 environment using julia1.6, version 0.1.1 works fine.  plz see the process below:
```
(@v1.6) pkg> st
      Status `~/.julia/environments/v1.6/Project.toml`
  [9a3f8284] Random

(@v1.6) pkg> add https://github.com/sonosole/WindowFunctions.jl.git#master
     Cloning git-repo `https://github.com/sonosole/WindowFunctions.jl.git`
    Updating git-repo `https://github.com/sonosole/WindowFunctions.jl.git`
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
    Updating `~/.julia/environments/v1.6/Project.toml`
  [f8d1b8c8] + WindowFunctions v0.1.1 `https://github.com/sonosole/WindowFunctions.jl.git#master`
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [f8d1b8c8] + WindowFunctions v0.1.1 `https://github.com/sonosole/WindowFunctions.jl.git#master`
Precompiling project...
  6 dependencies successfully precompiled in 15 seconds (6 already precompiled)

(@v1.6) pkg> st
      Status `~/.julia/environments/v1.6/Project.toml`
  [f8d1b8c8] WindowFunctions v0.1.1 `https://github.com/sonosole/WindowFunctions.jl.git#master`
  [9a3f8284] Random

julia> using WindowFunctions

julia> barthann(3, dtype=Float64)
3-element Vector{Float64}:
 0.0
 1.0
 0.0

julia> barthann(3, dtype=Float32)
3-element Vector{Float32}:
 0.0
 1.0
 0.0
```
I'm not sure if you had added this pkg successfully...  :/

**Comment by StefanPofahl** [comment]
here my package status:
```

(@v1.6) pkg> st
      Status `~/.julia/environments/v1.6/Project.toml`
  [c52e3926] Atom v0.12.38
  [6e4b80f9] BenchmarkTools v1.3.1
  [9e28174c] BinDeps v1.0.2
  [ad839575] Blink v0.12.5
  [...]
  [90137ffa] StaticArrays v1.5.9
  [2913bbd2] StatsBase v0.33.21
  [f8d1b8c8] WindowFunctions v0.1.1 `https://github.com/sonosole/WindowFunctions.jl.git#master`
  [fdbf4ff8] XLSX v0.8.4
  [de0858da] Printf
```
The mini example above give the same output for me.

Today I have re-run your example and now everything works fine :-)

What might be useful, is the advice to run your example outside the editor vscode/code.
Inside the code-REPL the GKS-window does not open on my machine.

**Comment by sonosole** [comment]
> here my package status:
> ```
> 
> (@v1.6) pkg> st
>       Status `~/.julia/environments/v1.6/Project.toml`
>   [c52e3926] Atom v0.12.38
>   [6e4b80f9] BenchmarkTools v1.3.1
>   [9e28174c] BinDeps v1.0.2
>   [ad839575] Blink v0.12.5
>   [...]
>   [90137ffa] StaticArrays v1.5.9
>   [2913bbd2] StatsBase v0.33.21
>   [f8d1b8c8] WindowFunctions v0.1.1 `https://github.com/sonosole/WindowFunctions.jl.git#master`
>   [fdbf4ff8] XLSX v0.8.4
>   [de0858da] Printf
> ```
> The mini example above give the same output for me.
> 
> Today I have re-run your example and now everything works fine :-)
> 
> What might be useful, is the advice to run your example outside the editor vscode/code.
> Inside the code-REPL the GKS-window does not open on my machine.

yeah, the Plots pkg may not be working on some machines.
